---
- name: Create code-server namespace
  kubernetes.core.k8s:
    name: code-server
    api_version: v1
    kind: Namespace
    state: present

- name: Clone code-server repository
  ansible.builtin.git:
    repo: https://github.com/coder/code-server
    dest: /tmp/code-server
    version: main
    force: true

- name: Install code-server using Helm
  kubernetes.core.helm:
    name: code-server
    chart_ref: /tmp/code-server/ci/helm-chart
    namespace: code-server
    state: present
    values:
      service:
        type: NodePort
        port: 8443
      persistence:
        enabled: true
        storageClass: openebs-hostpath
        size: 10Gi
      securityContext:
        enabled: true
        fsGroup: 1000
        runAsUser: 1000
      volumePermissions:
        enabled: true
        securityContext:
          runAsUser: 0
      extraArgs:
        - --cert=false
        - --bind-addr=0.0.0.0:8443
