---
- name: Create code-server namespace
  block:
    - name: Check if code-server namespace exists
      kubernetes.core.k8s_info:
        kind: Namespace
        name: code-server
      register: namespace_check
      changed_when: false
      ignore_errors: true

    - name: Create code-server namespace
      kubernetes.core.k8s:
        name: code-server
        api_version: v1
        kind: Namespace
        state: present
      when: namespace_check.resources | length == 0

- name: Clone code-server repository
  block:
    - name: Check if code-server repository exists
      ansible.builtin.stat:
        path: /tmp/code-server/ci/helm-chart
      register: repo_check
      changed_when: false

    - name: Clone code-server repository
      ansible.builtin.git:
        repo: https://github.com/coder/code-server
        dest: /tmp/code-server
        version: main
        force: true
      when: not repo_check.stat.exists

- name: Install or upgrade code-server using Helm
  kubernetes.core.helm:
    name: code-server
    chart_ref: /tmp/code-server/ci/helm-chart
    namespace: code-server
    state: present
    update_repo_cache: true
    values:
      service:
        type: NodePort
        port: 8080
      extraArgs:
        - --bind-addr=0.0.0.0:8080
      persistence:
        enabled: true
        storageClass: openebs-hostpath
        size: 10Gi
      securityContext:
        enabled: true
        fsGroup: 1000
        runAsUser: 1000
      volumePermissions:
        enabled: true
        securityContext:
          runAsUser: 0
      podAnnotations:
        checksum/config: "{{ lookup('pipe', 'date +%s') }}"
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "1Gi"
          cpu: "500m"

- name: Display code-server access URL
  block:
    - name: Get Node IP for code-server URL
      ansible.builtin.command:
        cmd: kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}'
      register: node_ip_result
      changed_when: false
      check_mode: false # Always run this to get info

    - name: Get NodePort for code-server URL
      ansible.builtin.command:
        cmd: kubectl get svc -n code-server code-server -o jsonpath='{.spec.ports[0].nodePort}'
      register: node_port_result
      changed_when: false
      check_mode: false # Always run this to get info

    - name: Display code-server access URL
      ansible.builtin.debug:
        msg: "You can access code-server at: http://{{ node_ip_result.stdout }}:{{ node_port_result.stdout }}"
      when: node_ip_result.stdout and node_port_result.stdout

- name: Display code-server password
  block:
    - name: Get code-server secret
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: code-server
        name: code-server # Assuming secret name matches Helm release name
      register: codeserver_secret_result
      changed_when: false
      check_mode: false # Always run this to get info

    - name: Decode and display code-server password
      ansible.builtin.debug:
        msg: "The code-server password is: {{ codeserver_secret_result.resources[0].data.password | b64decode }}"
      when:
        - codeserver_secret_result.resources is defined
        - codeserver_secret_result.resources | length > 0
        - codeserver_secret_result.resources[0].data.password is defined
      # no_log: true # Prevent password from being logged in Ansible output if verbose
