---
- name: Setup Kubernetes and deploy code-server
  hosts: localhost
  become: true
  become_method: sudo

  pre_tasks:
    - name: Check if kubernetes.core collection is installed
      command: ansible-galaxy collection list kubernetes.core
      register: collection_check
      ignore_errors: true
      changed_when: false

    - name: Install kubernetes.core collection
      command: ansible-galaxy collection install kubernetes.core
      when: collection_check.rc != 0

  roles:
    - kubernetes_local_cluster
    # - code_server 