---
- name: Check if Cilium CLI is installed
  ansible.builtin.command: which cilium
  register: cilium_cli_check
  changed_when: false
  ignore_errors: true

- name: Check if Cilium is running in cluster
  ansible.builtin.command: kubectl get pods -n kube-system -l k8s-app=cilium
  register: cilium_pods_check
  changed_when: false
  ignore_errors: true

- name: Set Cilium installation status
  ansible.builtin.set_fact:
    cilium_installed: "{{ cilium_cli_check.rc == 0 and 'cilium' in cilium_pods_check.stdout }}"

- name: Debug Cilium status
  ansible.builtin.debug:
    msg:
      - "Cilium CLI installed: {{ cilium_cli_check.rc == 0 }}"
      - "Cilium pods running: {{ 'cilium' in cilium_pods_check.stdout }}"
      - "Cilium fully installed: {{ cilium_installed }}"

- name: Install Cilium CLI
  when: not cilium_cli_check.rc == 0
  block:
    - name: Download Cilium CLI
      ansible.builtin.get_url:
        url: https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz
        dest: /tmp/cilium-linux-amd64.tar.gz
        mode: '0644'
      changed_when: true

    - name: Extract Cilium CLI
      ansible.builtin.unarchive:
        src: /tmp/cilium-linux-amd64.tar.gz
        dest: /usr/local/bin
        remote_src: true
      become: true
      changed_when: true

    - name: Clean up downloaded file
      ansible.builtin.file:
        path: /tmp/cilium-linux-amd64.tar.gz
        state: absent
      changed_when: true

- name: Install Cilium
  when: not cilium_installed
  ansible.builtin.command: cilium install --kubeconfig /etc/kubernetes/admin.conf
  changed_when: true
  register: cilium_install
  become: true

- name: Wait for Cilium to be ready
  ansible.builtin.command: cilium status --wait
  register: cilium_status
  retries: 20
  delay: 3
  until: cilium_status.rc == 0
  changed_when: false
