---
- name: Collection installation tasks
  ansible.builtin.import_tasks: collections.yml

- name: Tools installation tasks
  ansible.builtin.import_tasks: tools.yml

- name: Cluster and cilium installation tasks
  ansible.builtin.import_tasks: setup_cluster_and_cilium.yml

- name: Check if control-plane taint exists
  ansible.builtin.command: kubectl get nodes {{ ansible_hostname }} -o jsonpath='{.spec.taints[?(@.key=="node-role.kubernetes.io/control-plane")]}'
  register: taint_check
  changed_when: false
  ignore_errors: true

- name: Remove control-plane taint
  ansible.builtin.command: kubectl taint nodes {{ ansible_hostname }} node-role.kubernetes.io/control-plane-
  become: true
  changed_when: true
  when: taint_check.stdout != ""
