---
- name: Collection installation tasks
  ansible.builtin.import_tasks: collections.yml

- name: Tools installation tasks
  ansible.builtin.import_tasks: tools.yml

- name: New cluster tasks
  ansible.builtin.import_tasks: new_cluster.yml

- name: Cilium installation tasks
  ansible.builtin.import_tasks: cilium.yml

- name: Control plane taint removal tasks (enable scheduling worknodes)
  ansible.builtin.import_tasks: control_plane_enable_workload_scheduling.yml

- name: Storage setup tasks
  ansible.builtin.import_tasks: storage.yml
