---
# Check if required tools are installed
- name: Check if required tools are installed
  block:
    - name: Check kubectl installation status
      block:
        - name: Check if kubectl is installed
          ansible.builtin.command: which kubectl
          register: kubectl_check
          changed_when: false
          ignore_errors: true

        - name: Debug kubectl status
          ansible.builtin.debug:
            msg: "kubectl is {{ 'installed' if kubectl_check.rc == 0 else 'not installed' }}"

        - name: Install kubectl
          ansible.builtin.apt:
            name: kubectl
            state: present
            update_cache: true
          when: kubectl_check.rc != 0

    - name: Check kubeadm installation status
      block:
        - name: Check if kubeadm is installed
          ansible.builtin.command: which kubeadm
          register: kubeadm_check
          changed_when: false
          ignore_errors: true

        - name: Debug kubeadm status
          ansible.builtin.debug:
            msg: "kubeadm is {{ 'installed' if kubeadm_check.rc == 0 else 'not installed' }}"

        - name: Install kubeadm
          ansible.builtin.apt:
            name: kubeadm
            state: present
            update_cache: true
          when: kubeadm_check.rc != 0

    - name: Check kubelet installation status
      block:
        - name: Check if kubelet is installed
          ansible.builtin.command: which kubelet
          register: kubelet_check
          changed_when: false
          ignore_errors: true

        - name: Debug kubelet status
          ansible.builtin.debug:
            msg: "kubelet is {{ 'installed' if kubelet_check.rc == 0 else 'not installed' }}"

        - name: Install kubelet
          ansible.builtin.apt:
            name: kubelet
            state: present
            update_cache: true
          when: kubelet_check.rc != 0


