---
- name: Check kubectl installation status
  block:
    - name: Check if kubectl is installed
      ansible.builtin.command: which kubectl
      register: kubectl_check
      changed_when: false
      ignore_errors: true

    - name: Debug kubectl status
      ansible.builtin.debug:
        msg: "kubectl is {{ 'installed' if kubectl_check.rc == 0 else 'not installed' }}"

    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
        state: present
        update_cache: true
      when: kubectl_check.rc != 0
      become: true

- name: Check kubeadm installation status
  block:
    - name: Check if kubeadm is installed
      ansible.builtin.command: which kubeadm
      register: kubeadm_check
      changed_when: false
      ignore_errors: true

    - name: Debug kubeadm status
      ansible.builtin.debug:
        msg: "kubeadm is {{ 'installed' if kubeadm_check.rc == 0 else 'not installed' }}"

    - name: Install kubeadm
      ansible.builtin.apt:
        name: kubeadm
        state: present
        update_cache: true
      when: kubeadm_check.rc != 0
      become: true

- name: Check kubelet installation status
  block:
    - name: Check if kubelet is installed
      ansible.builtin.command: which kubelet
      register: kubelet_check
      changed_when: false
      ignore_errors: true

    - name: Debug kubelet status
      ansible.builtin.debug:
        msg: "kubelet is {{ 'installed' if kubelet_check.rc == 0 else 'not installed' }}"

    - name: Install kubelet
      ansible.builtin.apt:
        name: kubelet
        state: present
        update_cache: true
      when: kubelet_check.rc != 0
      become: true

- name: Install kubernetes Python package
  ansible.builtin.pip:
    name: kubernetes
    state: present
  become: true

- name: Setup Helm and plugins
  block:
    - name: Check if Helm is installed
      ansible.builtin.command: which helm
      register: helm_check
      changed_when: false
      ignore_errors: true

    - name: Download and extract Helm
      when: helm_check.rc != 0
      block:
        - name: Install Helm if not present
          ansible.builtin.get_url:
            url: https://get.helm.sh/helm-v3.14.3-linux-amd64.tar.gz
            dest: /tmp/helm.tar.gz
            mode: '0644'
          become: true

        - name: Extract Helm binary
          ansible.builtin.unarchive:
            src: /tmp/helm.tar.gz
            dest: /usr/local/bin
            remote_src: true
            extra_opts: [--strip-components=1]
          become: true

    - name: Check if helm-diff plugin is installed
      ansible.builtin.command: helm plugin list | grep diff
      register: helm_diff_check
      changed_when: false
      ignore_errors: true

    - name: Install helm-diff plugin
      kubernetes.core.helm_plugin:
        plugin_name: diff
        plugin_url: https://github.com/databus23/helm-diff
        plugin_version: v3.8.1
        state: present
      when: helm_diff_check.rc != 0
      become: true
 